[project]
name = "simplevllm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ajax0564", email = "ankit51200iit@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "huggingface-hub>=1.31.0",
    "safetensors>=0.8.0",
    "tokenizers>=0.23.2",
    "torch>=2.9.0",
    "transformers",
    "flash-attn",
]

[project.scripts]
simplevllm = "simplevllm:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
